services:

  static_hosting:
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./settings/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  backend:
    image: couchdb:3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    healthcheck:
      test: curl -f http://localhost:5984/_up || exit 1
      interval: 2s
      timeout: 3s

  accessible_backend:
    image: curlimages/curl
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        alias put="curl -X PUT -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'"
        put backend:5984/_node/nonode@nohost/_config/chttpd/enable_cors --data '"true"'
        put backend:5984/_node/nonode@nohost/_config/cors/origins --data '"*"'
        put backend:5984/helios
        put backend:5984/helios/_security --data '{"members":{"roles":[]},"admins":{"roles":["_admin"]}}'
    depends_on:
      backend:
        condition: service_healthy

  updated_samples:
    image: curlimages/curl
    entrypoint: ["/bin/sh","-c"]
    volumes:
      - ./frontend/public/sample_data.json:/sample_data.json
    command:
      - |
        curl -X POST http://backend:5984/helios/_bulk_docs -H "Content-Type: application/json" -d @/sample_data.json
    depends_on:
      accessible_backend:
        condition: service_completed_successfully
  
  index:
    image: curlimages/curl
    entrypoint: ["/bin/sh","-c"]
    volumes:
      - ./backend/by_date.json:/by_date.json
      - ./backend/by_date_and_city.json:/by_date_and_city.json
    command:
      - |
        curl -X POST http://backend:5984/helios/_index -H "Content-Type: application/json" -d @/by_date.json -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'
        curl -X POST http://backend:5984/helios/_index -H "Content-Type: application/json" -d @/by_date_and_city.json -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'
    depends_on:
      accessible_backend:
        condition: service_completed_successfully